package com.example.android.multmedia.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.android.multmedia.personaldb.MediaDb;

import com.example.android.multmedia.greendao.MediaDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mediaDbDaoConfig;

    private final MediaDbDao mediaDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mediaDbDaoConfig = daoConfigMap.get(MediaDbDao.class).clone();
        mediaDbDaoConfig.initIdentityScope(type);

        mediaDbDao = new MediaDbDao(mediaDbDaoConfig, this);

        registerDao(MediaDb.class, mediaDbDao);
    }
    
    public void clear() {
        mediaDbDaoConfig.clearIdentityScope();
    }

    public MediaDbDao getMediaDbDao() {
        return mediaDbDao;
    }

}
