package com.example.android.multmedia.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.android.multmedia.playedlist.personaldb.MediaDb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEDIA_DB".
*/
public class MediaDbDao extends AbstractDao<MediaDb, Long> {

    public static final String TABLENAME = "MEDIA_DB";

    /**
     * Properties of entity MediaDb.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property MediaPath = new Property(1, String.class, "mediaPath", false, "MEDIA_PATH");
        public final static Property MediaName = new Property(2, String.class, "mediaName", false, "MEDIA_NAME");
        public final static Property Size = new Property(3, long.class, "size", false, "SIZE");
        public final static Property MediaId = new Property(4, long.class, "mediaId", false, "MEDIA_ID");
        public final static Property CreateTime = new Property(5, long.class, "createTime", false, "CREATE_TIME");
        public final static Property MediaType = new Property(6, int.class, "mediaType", false, "MEDIA_TYPE");
        public final static Property IsFavor = new Property(7, boolean.class, "isFavor", false, "IS_FAVOR");
        public final static Property PlayedTime = new Property(8, long.class, "playedTime", false, "PLAYED_TIME");
        public final static Property PlayedCounts = new Property(9, int.class, "playedCounts", false, "PLAYED_COUNTS");
    }


    public MediaDbDao(DaoConfig config) {
        super(config);
    }
    
    public MediaDbDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEDIA_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"MEDIA_PATH\" TEXT NOT NULL ," + // 1: mediaPath
                "\"MEDIA_NAME\" TEXT," + // 2: mediaName
                "\"SIZE\" INTEGER NOT NULL ," + // 3: size
                "\"MEDIA_ID\" INTEGER NOT NULL ," + // 4: mediaId
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 5: createTime
                "\"MEDIA_TYPE\" INTEGER NOT NULL ," + // 6: mediaType
                "\"IS_FAVOR\" INTEGER NOT NULL ," + // 7: isFavor
                "\"PLAYED_TIME\" INTEGER NOT NULL ," + // 8: playedTime
                "\"PLAYED_COUNTS\" INTEGER NOT NULL );"); // 9: playedCounts
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEDIA_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MediaDb entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getMediaPath());
 
        String mediaName = entity.getMediaName();
        if (mediaName != null) {
            stmt.bindString(3, mediaName);
        }
        stmt.bindLong(4, entity.getSize());
        stmt.bindLong(5, entity.getMediaId());
        stmt.bindLong(6, entity.getCreateTime());
        stmt.bindLong(7, entity.getMediaType());
        stmt.bindLong(8, entity.getIsFavor() ? 1L: 0L);
        stmt.bindLong(9, entity.getPlayedTime());
        stmt.bindLong(10, entity.getPlayedCounts());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MediaDb entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getMediaPath());
 
        String mediaName = entity.getMediaName();
        if (mediaName != null) {
            stmt.bindString(3, mediaName);
        }
        stmt.bindLong(4, entity.getSize());
        stmt.bindLong(5, entity.getMediaId());
        stmt.bindLong(6, entity.getCreateTime());
        stmt.bindLong(7, entity.getMediaType());
        stmt.bindLong(8, entity.getIsFavor() ? 1L: 0L);
        stmt.bindLong(9, entity.getPlayedTime());
        stmt.bindLong(10, entity.getPlayedCounts());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public MediaDb readEntity(Cursor cursor, int offset) {
        MediaDb entity = new MediaDb( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // mediaPath
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mediaName
            cursor.getLong(offset + 3), // size
            cursor.getLong(offset + 4), // mediaId
            cursor.getLong(offset + 5), // createTime
            cursor.getInt(offset + 6), // mediaType
            cursor.getShort(offset + 7) != 0, // isFavor
            cursor.getLong(offset + 8), // playedTime
            cursor.getInt(offset + 9) // playedCounts
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MediaDb entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setMediaPath(cursor.getString(offset + 1));
        entity.setMediaName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSize(cursor.getLong(offset + 3));
        entity.setMediaId(cursor.getLong(offset + 4));
        entity.setCreateTime(cursor.getLong(offset + 5));
        entity.setMediaType(cursor.getInt(offset + 6));
        entity.setIsFavor(cursor.getShort(offset + 7) != 0);
        entity.setPlayedTime(cursor.getLong(offset + 8));
        entity.setPlayedCounts(cursor.getInt(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MediaDb entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MediaDb entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MediaDb entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
